# Generated by Django 4.1 on 2022-08-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StickynoteInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3000)),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.TextField(max_length=500)),
            ],
        ),
    ]
