# Generated by Django 4.1 on 2022-08-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickynote', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stickynoteinput',
            name='date',
        ),
        migrations.AlterField(
            model_name='stickynoteinput',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
