# Generated by Django 4.1 on 2022-08-23 17:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stickynote', '0002_remove_stickynoteinput_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stickynoteinput',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
