# Generated by Django 4.0.6 on 2022-08-24 21:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stickynote', '0004_stickynoteinput_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='stickynoteinput',
            name='link',
            field=models.CharField(default=django.utils.timezone.now, max_length=5000),
            preserve_default=False,
        ),
    ]
