# Generated by Django 4.0.6 on 2022-08-24 22:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stickynote', '0006_alter_stickynoteinput_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stickynoteinput',
            name='link',
        ),
        migrations.AddField(
            model_name='stickynoteinput',
            name='weblink',
            field=models.CharField(default=django.utils.timezone.now, max_length=5000),
            preserve_default=False,
        ),
    ]
